### ISSUE TITLE
402 error on xhr request due to missing bearer token

### ISSUE THREAD

**Issue by AndriesRombouts** [fulippo/share-your-garmin-workout#6]
In noticed on 22/10/2023 that the download button was missing. When debugging the code it became clear that the xhr request to load the json file for the workout and that is used as the trigger to inject the button is now failing with a 402 code. A quick check resulted in the observation that the xhr request is missing a bearer Authorization header.
The token itself is available in local storage so it can be added to the request

**Comment by fulippo** [comment]
Hi @AndriesRombouts, thank you for your analysis. I am working on a [PR to properly fix the changes in their APIs](https://github.com/fulippo/share-your-garmin-workout/pull/7)

**Comment by fulippo** [comment]
A new release of the extension has been sent for revision to Google. Should be added soon. Closing the issue
